language: ruby
node_js:
  - 0.10
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install -g bower karma
script:
  - bower install
  - bundle exec middleman build
  - karma start --single-run --browsers Firefox
deploy:
  provider: divshot
  environment:
    master: development
    staging: staging
    production: production
  skip_cleanup: true
  api_key:
    secure: HsfkvkDfvQ8yGxX77HQyKP5oRpZxKxyq977yomdxFaOFNKKzCJLXZemEaqwzEB6JkCp/VWGywdJxtzly0gaelxDi/VMp0PuL8tYnj5hVt8xSJgCO/+17+nbsVJnZJVZiLzQr4fL86YyFSJyhS+t0dnY+I/aILgsIwguY62UoJs0=
